name: Build stable version and draft release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release (e.g., 1.0.0)"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure project (Win32)
        run: cmake -S . -B build -A Win32

      - name: Build project (Release, x86)
        run: cmake --build build --config Release

      - name: Generate Release Notes Body
        id: notes
        shell: pwsh
        run: .\.github\workflows\changelog_generator.ps1 -Tag "${{ github.event.inputs.tag }}" -Repository "${{ github.repository }}"

      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          draft: true
          artifacts: |
            output/*.asi
          replacesArtifacts: true
          body: ${{ steps.notes.outputs.body }}
